/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_leads_service_areas = pgEnum('enum_leads_service_areas', [
  'devops',
  'uzemeltetes',
  'fejlesztes',
  'other',
])
export const enum_leads_interactions_type = pgEnum('enum_leads_interactions_type', [
  'email',
  'phone',
  'meeting',
  'task',
  'other',
])
export const enum_leads_quotes_type = pgEnum('enum_leads_quotes_type', ['fix', 'hourly'])
export const enum_leads_quotes_quote_status = pgEnum('enum_leads_quotes_quote_status', [
  'none',
  'accepted',
  'rejected',
])
export const enum_leads_status = pgEnum('enum_leads_status', [
  'uj',
  'kickoff_meeting',
  'helyszini_szemle',
  'arajanlatra_var',
  'arajanlat_elkuldve',
  'meeting',
  'arajanlat_elfogadva',
  'arajanlat_elutasitva',
  'ugyfel_visszautasitotta',
  'alvomod',
])
export const enum_leads_priority = pgEnum('enum_leads_priority', [
  'alacsony',
  'kozepes',
  'magas',
  'kiemelt',
])
export const enum_tasks_status = pgEnum('enum_tasks_status', [
  'new',
  'inprogress',
  'delayed',
  'done',
])
export const enum_tasks_priority = pgEnum('enum_tasks_priority', [
  'alacsony',
  'kozepes',
  'magas',
  'kiemelt',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const leads_service_areas = pgTable(
  'leads_service_areas',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_leads_service_areas('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('leads_service_areas_order_idx').on(columns.order),
    index('leads_service_areas_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [leads.id],
      name: 'leads_service_areas_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const leads_interactions = pgTable(
  'leads_interactions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    type: enum_leads_interactions_type('type').notNull(),
    description: varchar('description'),
    task: integer('task_id').references(() => tasks.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('leads_interactions_order_idx').on(columns._order),
    index('leads_interactions_parent_id_idx').on(columns._parentID),
    index('leads_interactions_task_idx').on(columns.task),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [leads.id],
      name: 'leads_interactions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const leads_quotes = pgTable(
  'leads_quotes',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    type: enum_leads_quotes_type('type').notNull(),
    sentAt: timestamp('sent_at', { mode: 'string', withTimezone: true, precision: 3 }),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    currency: varchar('currency').notNull().default('HUF'),
    quoteStatus: enum_leads_quotes_quote_status('quote_status').default('none'),
    notes: varchar('notes'),
  },
  (columns) => [
    index('leads_quotes_order_idx').on(columns._order),
    index('leads_quotes_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [leads.id],
      name: 'leads_quotes_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const leads_history_changes = pgTable(
  'leads_history_changes',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    field: varchar('field').notNull(),
    from: varchar('from'),
    to: varchar('to'),
  },
  (columns) => [
    index('leads_history_changes_order_idx').on(columns._order),
    index('leads_history_changes_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [leads_history.id],
      name: 'leads_history_changes_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const leads_history = pgTable(
  'leads_history',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('leads_history_order_idx').on(columns._order),
    index('leads_history_parent_id_idx').on(columns._parentID),
    index('leads_history_user_idx').on(columns.user),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [leads.id],
      name: 'leads_history_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const leads = pgTable(
  'leads',
  {
    id: serial('id').primaryKey(),
    client_name: varchar('client_name').notNull(),
    client_contact1: varchar('client_contact1'),
    client_contact2: varchar('client_contact2'),
    client_country: varchar('client_country'),
    client_city: varchar('client_city'),
    status: enum_leads_status('status').notNull().default('uj'),
    priority: enum_leads_priority('priority').default('alacsony'),
    owner: integer('owner_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    note: varchar('note'),
    deadline: timestamp('deadline', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('leads_owner_idx').on(columns.owner),
    index('leads_updated_at_idx').on(columns.updatedAt),
    index('leads_created_at_idx').on(columns.createdAt),
  ],
)

export const leads_rels = pgTable(
  'leads_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('leads_rels_order_idx').on(columns.order),
    index('leads_rels_parent_idx').on(columns.parent),
    index('leads_rels_path_idx').on(columns.path),
    index('leads_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [leads.id],
      name: 'leads_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'leads_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const tasks_notes = pgTable(
  'tasks_notes',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    text: varchar('text').notNull(),
  },
  (columns) => [
    index('tasks_notes_order_idx').on(columns._order),
    index('tasks_notes_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tasks.id],
      name: 'tasks_notes_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tasks_history_changes = pgTable(
  'tasks_history_changes',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    field: varchar('field').notNull(),
    from: varchar('from'),
    to: varchar('to'),
  },
  (columns) => [
    index('tasks_history_changes_order_idx').on(columns._order),
    index('tasks_history_changes_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tasks_history.id],
      name: 'tasks_history_changes_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tasks_history = pgTable(
  'tasks_history',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('tasks_history_order_idx').on(columns._order),
    index('tasks_history_parent_id_idx').on(columns._parentID),
    index('tasks_history_user_idx').on(columns.user),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tasks.id],
      name: 'tasks_history_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tasks = pgTable(
  'tasks',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    status: enum_tasks_status('status').notNull().default('new'),
    deadline: timestamp('deadline', { mode: 'string', withTimezone: true, precision: 3 }),
    owner: integer('owner_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    priority: enum_tasks_priority('priority').notNull().default('alacsony'),
    notificationAt: timestamp('notification_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    tag: varchar('tag'),
    isLead: boolean('is_lead').default(false),
    leadsEntry: integer('leads_entry_id').references(() => leads.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('tasks_owner_idx').on(columns.owner),
    index('tasks_leads_entry_idx').on(columns.leadsEntry),
    index('tasks_updated_at_idx').on(columns.updatedAt),
    index('tasks_created_at_idx').on(columns.createdAt),
  ],
)

export const tasks_rels = pgTable(
  'tasks_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('tasks_rels_order_idx').on(columns.order),
    index('tasks_rels_parent_idx').on(columns.parent),
    index('tasks_rels_path_idx').on(columns.path),
    index('tasks_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tasks.id],
      name: 'tasks_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'tasks_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    leadsID: integer('leads_id'),
    tasksID: integer('tasks_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_leads_id_idx').on(columns.leadsID),
    index('payload_locked_documents_rels_tasks_id_idx').on(columns.tasksID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['leadsID']],
      foreignColumns: [leads.id],
      name: 'payload_locked_documents_rels_leads_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tasksID']],
      foreignColumns: [tasks.id],
      name: 'payload_locked_documents_rels_tasks_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_leads_service_areas = relations(leads_service_areas, ({ one }) => ({
  parent: one(leads, {
    fields: [leads_service_areas.parent],
    references: [leads.id],
    relationName: 'serviceAreas',
  }),
}))
export const relations_leads_interactions = relations(leads_interactions, ({ one }) => ({
  _parentID: one(leads, {
    fields: [leads_interactions._parentID],
    references: [leads.id],
    relationName: 'interactions',
  }),
  task: one(tasks, {
    fields: [leads_interactions.task],
    references: [tasks.id],
    relationName: 'task',
  }),
}))
export const relations_leads_quotes = relations(leads_quotes, ({ one }) => ({
  _parentID: one(leads, {
    fields: [leads_quotes._parentID],
    references: [leads.id],
    relationName: 'quotes',
  }),
}))
export const relations_leads_history_changes = relations(leads_history_changes, ({ one }) => ({
  _parentID: one(leads_history, {
    fields: [leads_history_changes._parentID],
    references: [leads_history.id],
    relationName: 'changes',
  }),
}))
export const relations_leads_history = relations(leads_history, ({ one, many }) => ({
  _parentID: one(leads, {
    fields: [leads_history._parentID],
    references: [leads.id],
    relationName: 'history',
  }),
  user: one(users, {
    fields: [leads_history.user],
    references: [users.id],
    relationName: 'user',
  }),
  changes: many(leads_history_changes, {
    relationName: 'changes',
  }),
}))
export const relations_leads_rels = relations(leads_rels, ({ one }) => ({
  parent: one(leads, {
    fields: [leads_rels.parent],
    references: [leads.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [leads_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_leads = relations(leads, ({ one, many }) => ({
  serviceAreas: many(leads_service_areas, {
    relationName: 'serviceAreas',
  }),
  owner: one(users, {
    fields: [leads.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  interactions: many(leads_interactions, {
    relationName: 'interactions',
  }),
  quotes: many(leads_quotes, {
    relationName: 'quotes',
  }),
  history: many(leads_history, {
    relationName: 'history',
  }),
  _rels: many(leads_rels, {
    relationName: '_rels',
  }),
}))
export const relations_tasks_notes = relations(tasks_notes, ({ one }) => ({
  _parentID: one(tasks, {
    fields: [tasks_notes._parentID],
    references: [tasks.id],
    relationName: 'notes',
  }),
}))
export const relations_tasks_history_changes = relations(tasks_history_changes, ({ one }) => ({
  _parentID: one(tasks_history, {
    fields: [tasks_history_changes._parentID],
    references: [tasks_history.id],
    relationName: 'changes',
  }),
}))
export const relations_tasks_history = relations(tasks_history, ({ one, many }) => ({
  _parentID: one(tasks, {
    fields: [tasks_history._parentID],
    references: [tasks.id],
    relationName: 'history',
  }),
  user: one(users, {
    fields: [tasks_history.user],
    references: [users.id],
    relationName: 'user',
  }),
  changes: many(tasks_history_changes, {
    relationName: 'changes',
  }),
}))
export const relations_tasks_rels = relations(tasks_rels, ({ one }) => ({
  parent: one(tasks, {
    fields: [tasks_rels.parent],
    references: [tasks.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [tasks_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_tasks = relations(tasks, ({ one, many }) => ({
  notes: many(tasks_notes, {
    relationName: 'notes',
  }),
  owner: one(users, {
    fields: [tasks.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  leadsEntry: one(leads, {
    fields: [tasks.leadsEntry],
    references: [leads.id],
    relationName: 'leadsEntry',
  }),
  history: many(tasks_history, {
    relationName: 'history',
  }),
  _rels: many(tasks_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    leadsID: one(leads, {
      fields: [payload_locked_documents_rels.leadsID],
      references: [leads.id],
      relationName: 'leads',
    }),
    tasksID: one(tasks, {
      fields: [payload_locked_documents_rels.tasksID],
      references: [tasks.id],
      relationName: 'tasks',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_leads_service_areas: typeof enum_leads_service_areas
  enum_leads_interactions_type: typeof enum_leads_interactions_type
  enum_leads_quotes_type: typeof enum_leads_quotes_type
  enum_leads_quotes_quote_status: typeof enum_leads_quotes_quote_status
  enum_leads_status: typeof enum_leads_status
  enum_leads_priority: typeof enum_leads_priority
  enum_tasks_status: typeof enum_tasks_status
  enum_tasks_priority: typeof enum_tasks_priority
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  leads_service_areas: typeof leads_service_areas
  leads_interactions: typeof leads_interactions
  leads_quotes: typeof leads_quotes
  leads_history_changes: typeof leads_history_changes
  leads_history: typeof leads_history
  leads: typeof leads
  leads_rels: typeof leads_rels
  tasks_notes: typeof tasks_notes
  tasks_history_changes: typeof tasks_history_changes
  tasks_history: typeof tasks_history
  tasks: typeof tasks
  tasks_rels: typeof tasks_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_leads_service_areas: typeof relations_leads_service_areas
  relations_leads_interactions: typeof relations_leads_interactions
  relations_leads_quotes: typeof relations_leads_quotes
  relations_leads_history_changes: typeof relations_leads_history_changes
  relations_leads_history: typeof relations_leads_history
  relations_leads_rels: typeof relations_leads_rels
  relations_leads: typeof relations_leads
  relations_tasks_notes: typeof relations_tasks_notes
  relations_tasks_history_changes: typeof relations_tasks_history_changes
  relations_tasks_history: typeof relations_tasks_history
  relations_tasks_rels: typeof relations_tasks_rels
  relations_tasks: typeof relations_tasks
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
